[project]
name = "linkshortener"
version = "0.1.0"
description = ""
authors = [
    {name = "iltsy26",email = "ilya.tsiban@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.54.0,<0.55.0)"
]

[tool.poetry]
packages = [{include = "linkshortener", from = "src"}]

[tool.poetry.scripts]
app = "linkshortener.main:start"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

